<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="inertial_macros.xacro" />
  <xacro:include filename="dimensions_macros.xacro" />
  <xacro:include filename="materials_macros.xacro" />

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
      <origin xyz="0 0 -${chassis_height/2}" rpy="0 0 0" />
      <material name="blue" />
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
      <origin xyz="0 0 -${chassis_height/2}" rpy="0 0 0" />
    </collision>
    <xacro:inertial_box mass="${chassis_weight}" x="${chassis_length}" y="${chassis_width}"
      z="${chassis_height}">
      <origin xyz="0 0 -${chassis_height/2}" rpy="0 0 0" />
    </xacro:inertial_box>
  </link>

  <!-- WHEELS -->
  <link name="fl_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
    </collision>
    <xacro:inertial_cylinder mass="0.05" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="1.57 0 0" />
    </xacro:inertial_cylinder>
  </link>
  <joint name="fl_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="fl_wheel_link" />
    <origin xyz="${wheel_offset_length} ${wheel_offset_width} ${wheel_offset_height}"
      rpy="0 0 0" />
    <axis xyz="0 1 0 " />
  </joint>

  <link name="fr_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
    </collision>
    <xacro:inertial_cylinder mass="0.05" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="1.57 0 0" />
    </xacro:inertial_cylinder>
  </link>
  <joint name="fr_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="fr_wheel_link" />
    <origin xyz="${wheel_offset_length} ${-wheel_offset_width} ${wheel_offset_height}"
      rpy="0 0 0" />
    <axis xyz="0 1 0 " />
  </joint>




  <link name="rl_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
    </collision>
    <xacro:inertial_cylinder mass="0.05" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="1.57 0 0" />
    </xacro:inertial_cylinder>
  </link>
  <joint name="rl_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="rl_wheel_link" />
    <origin xyz="${-wheel_offset_length} ${wheel_offset_width} ${wheel_offset_height}"
      rpy="0 0 0" />
    <axis xyz="0 1 0 " />
  </joint>

  <link name="rr_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
    </collision>
    <xacro:inertial_cylinder mass="0.05" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="1.57 0 0" />
    </xacro:inertial_cylinder>
  </link>
  <joint name="rr_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="rr_wheel_link" />
    <origin xyz="${-wheel_offset_length} ${-wheel_offset_width} ${wheel_offset_height}"
      rpy="0 0 0" />
    <axis xyz="0 1 0 " />
  </joint>








  <!-- BASE FOOTPRINT -->
  <link name="base_footprint" />
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${wheel_radius-wheel_offset_height}" rpy="0 0 0" />
  </joint>


</robot>